version: "3.7"
services:
  db:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=chat
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db